sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mduran/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true mduran/docker-react npm run test -- --coverage