sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mduran/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true mduran/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-721175356898"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY